/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pc.controller.server;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sameer
 */
public class DatabaseViewerInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DatabaseViewerInternalFrame
     */
    public DatabaseViewerInternalFrame() {
        initComponents();
    }
    
    public void displayAllLogs(){
        ArrayList <UserLogDetails> uldList = new DBHandler().getLogDetails();
        DefaultTableModel model = (DefaultTableModel) jTableDBData.getModel();
        Object[] row = new Object[8];
        for(int i=0;i<uldList.size();i++){
            row[0] = uldList.get(i).getUsername();
            row[1] = uldList.get(i).getSessionStrtTime();
            row[2] = uldList.get(i).getSessionStrtDate();
            row[3] = uldList.get(i).getActivity_name();
            row[4] = uldList.get(i).getActStartDate();
            row[5] = uldList.get(i).getActStartTime();
            row[6] = uldList.get(i).getActEndTime();
            row[7] = uldList.get(i).getActEndDate();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDBData = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Users Log");
        setAutoscrolls(true);

        jTableDBData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 225, 127), new java.awt.Color(0, 225, 127), new java.awt.Color(0, 225, 127), new java.awt.Color(0, 225, 127)));
        jTableDBData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Session Start Time", "Session Start Date", "Activity name", "Activity start date", "Activity start time", "Activity End time", "Activity End date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDBData.setGridColor(new java.awt.Color(0, 225, 127));
        jTableDBData.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTableDBData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDBData;
    // End of variables declaration//GEN-END:variables
}
